# Generated by Django 4.1.1 on 2022-10-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pwd",
            field=models.CharField(default="", max_length=32),
        ),
    ]
