# Generated by Django 4.1.1 on 2022-10-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0002_user_pwd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user", name="name", field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="user",
            name="pwd",
            field=models.CharField(default="", max_length=64),
        ),
    ]
